music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns = [
    #/music/
    url(r'^$', views.index, name='index'),
    #/music/712/
    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail')
]

website/urls.py
from django.contrib import admin
from django.conf.urls import include, url

urlpatterns = [
    url('admin/', admin.site.urls),
    url('music/', include('music.urls')),
]

music/models.py
from django.db import models

class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def __str__(self):
        return self.album_title+' - '+self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=500)

    def __str__(self):
        return self.song_title

music/views.py
from django.shortcuts import render, get_object_or_404
from .models import Album

#music -> templates -> music -> index.html

def index(request):
    all_albums = Album.objects.all()
    return render(request, 'music/pages/index.html', {'all_albums': all_albums})

def detail(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    return render(request, 'music/pages/detail.html', {'album': album})

music/templates/music/inc/navbar.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <a class="navbar-brand" href="/"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="">About</a>
            </li>
        </ul>

    </div>
</nav>

music/templates/music/layouts/base.html
<!-- Loads the path to your static files -->
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'music/css/style.css' %}">
</head>
    <body>

    {% include 'music/inc/navbar.html' %}

    <div class="container">
        {% block content %}{% endblock %}
    </div>
    </body>
</html>

music/templates/music/pages/detail.html
{% extends 'music/layouts/base.html' %}

{% block content %}
    <img src="{{ album.album_logo }}" alt="">
    <h1>{{ album.album_title }}</h1>
    <h3>{{ album.artist }}</h3>

    {% for song in album.song_set.all %}
        <li>{{ song.song_title }}</li>
    {% endfor %}
{% endblock %}

music/templates/music/pages/index.html
{% extends 'music/layouts/base.html' %}

{% block content %}
    {% if all_albums %}
        <ul>
            {% for album in all_albums %}
                <li><a href="{% url 'music:detail' album.id %}">{{ album.album_title }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No Album Found</p>
    {% endif %}
{% endblock %}